OnlineAdmissionSystem/Models/Application.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace OnlineAdmissionSystem.Models
{
    public class Application
    {
        [ForeignKey("User")]
        [Display(Name = "Email")]
        public string ApplicationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Display(Name = "Mobile Number")]
        public string TelePhoneNumber { get; set; }
        public byte[] Photo { get; set; }

        [Display(Name = "Department")]
        public int? DepartmentId { get; set; }
        public Department Department { get; set; }

        [Display(Name = "Program")]
        public int? ProgramId { get; set; }
        public Program Program { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Registration Date")]
        public DateTime? RegistrationDate { get; set; }

        //[Column("Status")]
        //public string StatusString
        //{
        //    get { return Status.ToString(); }
        //    private set { Status = (Status)Enum.Parse(typeof(Status), value); }
        //}

        //[NotMapped]
        public Status Status { get; set; }

        public ICollection<EducationDetail> EducationDetails { get; set; }
        public ICollection<EnclosedDocument> EnclosedDocuments { get; set; }

        public virtual ApplicationUser User { get; set; }

    }
}

OnlineAdmissionSystem/Models/ApplicationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineAdmissionSystem.Models
{
    public class ApplicationViewModel
    {
        public string ApplicationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TelePhoneNumber { get; set; }
        public HttpPostedFileBase Photo { get; set; }
        public byte[] PhotoDB { get; set; }

        public int? DepartmentId { get; set; }
        public Department Department { get; set; }

        public int? ProgramId { get; set; }
        public Program Program { get; set; }

        [Display(Name = "Registration Date")]
        public DateTime? RegistrationDate { get; set; }

        //[Column("Status")]
        //public string StatusString
        //{
        //    get { return Status.ToString(); }
        //    private set { Status = (Status)Enum.Parse(typeof(Status), value); }
        //}

        //[NotMapped]
        public Status Status { get; set; }

        public virtual ApplicationUser User { get; set; }

    }
}

OnlineAdmissionSystem/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using OnlineAdmissionSystem.Helpers;
using OnlineAdmissionSystem.Models;
using PagedList;

namespace OnlineAdmissionSystem.Controllers
{
    public class ApplicationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Applications
        //public ActionResult Index()currentFilter
        public ActionResult Index(string sortDir, string searchString, string currentFilter, int? page, string sortOrder = "")
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.currentFilter = searchString;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var applications = db.Applications.Include(a => a.Department).Include(a => a.Program).Include(a => a.User).AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                applications = applications.Where(p => p.FirstName.ToLower().Contains(searchString.ToLower())||
                p.LastName.ToLower().Contains(searchString.ToLower()) || 
                p.User.Email.ToLower().Contains(searchString.ToLower()) ||
                p.Department.Name.ToLower().Contains(searchString.ToLower()) ||
                p.Program.Name.ToLower().Contains(searchString.ToLower())
                );
            }

            switch (sortOrder.ToLower())
            {
                case "email":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.User.Email);
                    else
                        applications = applications.OrderBy(s => s.User.Email);
                    break;
                case "firstname":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.FirstName);
                    else
                        applications = applications.OrderBy(s => s.FirstName);
                    break;
                case "lastname":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.LastName);
                    else
                        applications = applications.OrderBy(s => s.LastName);
                    break;
                case "telephonenumber":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.TelePhoneNumber);
                    else
                        applications = applications.OrderBy(s => s.TelePhoneNumber);
                    break;
                case "department":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.DepartmentId);
                    else
                        applications = applications.OrderBy(s => s.DepartmentId);
                    break;
                case "program":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.ProgramId);
                    else
                        applications = applications.OrderBy(s => s.ProgramId);
                    break;
                case "registrationdate":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.RegistrationDate);
                    else
                        applications = applications.OrderBy(s => s.RegistrationDate);
                    break;
                case "status":
                    if (sortDir.ToLower() == "desc")
                        applications = applications.OrderByDescending(s => s.Status);
                    else
                        applications = applications.OrderBy(s => s.Status);
                    break;
                default:
                    applications = applications.OrderBy(s => s.FirstName);
                    break;
            }

            //var applications = db.Applications.Include(a => a.Department).Include(a => a.Program).Include(a => a.User);
            if (!User.IsInRole(RoleName.CanManage))
            {
                var Id = db.Users.Where(u => u.Email == User.Identity.Name).SingleOrDefault().Id;
                applications = db.Applications.Include(a => a.Department).Include(a => a.Program).Where(a => a.ApplicationId == Id);
                return View("SingleApplicationView", applications);
            }

            int pageSize = 2;
            int pageNumber = (page ?? 1);
            var data = applications.ToPagedList(pageNumber, pageSize);
            if (Request.IsAjaxRequest())
            {
                return this.PartialView("_SearchList", data);
            }
            else
            {
                return View(data);
            }

            //return View(applications.ToList());
        }

        // GET: Applications/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            application.Program = db.Programs.Where(p => p.ProgramId == application.ProgramId).SingleOrDefault();
            application.Department = db.Departments.Where(d => d.DepartmentId == application.Program.DepartmentId).SingleOrDefault();
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }


        public ActionResult EducationDetails(string id)
        {
            ViewBag.Id = id;
            var educationDetails = db.EducationDetails.Include(e => e.Application).Where(e => e.ApplicationId == id);
            return View(educationDetails.ToList());
        }

        public ActionResult EnclosedDocuments(string id)
        {
            ViewBag.Id = id;
            var enclosedDocuments = db.EnclosedDocuments.Include(e => e.Application).Where(e => e.ApplicationId == id);
            return View(enclosedDocuments.ToList());
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name");
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "Name");
            if (User.IsInRole(RoleName.CanManage))
            {
                ViewBag.ApplicationId = new SelectList(db.Users.Where(u => u.Email != null), "Id", "Email");
            }
            else
            {
                ViewBag.ApplicationId = new SelectList(db.Users.Where(u => u.Email == User.Identity.Name), "Id", "Email"); ;
            }
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationId,FirstName,LastName,TelePhoneNumber,Photo,DepartmentId,ProgramId,RegistrationDate,Status")] ApplicationViewModel applicationVM)
        {
            if (ModelState.IsValid)
            {
                //Mapper.CreateMap<ApplicationViewModel, Application>();
                //var application = Mapper.Map<Application>(applicationVM);
                var application = new Application();
                application.ApplicationId = applicationVM.ApplicationId;
                application.ProgramId = applicationVM.ProgramId;
                application.FirstName = applicationVM.FirstName;
                application.LastName = applicationVM.LastName;
                application.TelePhoneNumber = applicationVM.TelePhoneNumber;
                application.RegistrationDate = DateTime.Now;
                application.ProgramId = applicationVM.ProgramId;
                application.DepartmentId = db.Programs.Where(p => p.ProgramId == applicationVM.ProgramId).FirstOrDefault().DepartmentId;
                application.Status = Status.Draft;
                if (applicationVM.Photo != null)
                    application.Photo = ImageConverter.ByteArrayFromPostedFile(applicationVM.Photo);
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", applicationVM.DepartmentId);
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "Name", applicationVM.ProgramId);
            ViewBag.ApplicationId = new SelectList(db.Users, "Id", "Email", applicationVM.ApplicationId);
            return View(applicationVM);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.DepartmentId = new SelectList(db.Departments, "DepartmentId", "Name", application.DepartmentId);
            ViewBag.ProgramId = new SelectList(db.Programs, "ProgramId", "Name", application.ProgramId);
            if (User.IsInRole(RoleName.CanManage))
            {
                ViewBag.ApplicationId = new SelectList(db.Users.Where(u => u.Email != null), "Id", "Email");

OnlineAdmissionSystem/Controllers/EducationDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineAdmissionSystem.Models;

namespace OnlineAdmissionSystem.Controllers
{
    public class EducationDetailsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        

        // GET: EducationDetails
        public ActionResult Index()
        {
            var educationDetails = db.EducationDetails.Include(e => e.Application);
            return View(educationDetails.ToList());
        }

        // GET: EducationDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            return View(educationDetail);
        }

        // GET: EducationDetails/Create
        public ActionResult Create()
        {
            var Id = db.Users.Where(u => u.Email == User.Identity.Name).SingleOrDefault().Id;
            ViewBag.ApplicationId = new SelectList(db.Applications.Where(a=>a.ApplicationId == Id), "ApplicationId", "FirstName");
            return View();
        }

        // POST: EducationDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ApplicationId,Qualification,Year,Duration,BoardUniversity,Subjects,Percentage")] EducationDetail educationDetail)
        {
            if (ModelState.IsValid)
            {
                db.EducationDetails.Add(educationDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            return View(educationDetail);
        }

        // GET: EducationDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            return View(educationDetail);
        }

        // POST: EducationDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationId,Qualification,Year,Duration,BoardUniversity,Subjects,Percentage")] EducationDetail educationDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(educationDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationId = new SelectList(db.Applications, "ApplicationId", "FirstName", educationDetail.ApplicationId);
            return View(educationDetail);
        }

        // GET: EducationDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            if (educationDetail == null)
            {
                return HttpNotFound();
            }
            return View(educationDetail);
        }

        // POST: EducationDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EducationDetail educationDetail = db.EducationDetails.Find(id);
            db.EducationDetails.Remove(educationDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OnlineAdmissionSystem/Views/Applications/Create.cshtml
@model OnlineAdmissionSystem.Models.Application

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Applications", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Application</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationId, "ApplicationId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ApplicationId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ApplicationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelePhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramId, "ProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineAdmissionSystem/Views/Applications/Delete.cshtml
@using OnlineAdmissionSystem.Helpers
@model OnlineAdmissionSystem.Models.Application

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelePhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelePhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @if (Model.Photo != null)
            {
                @Html.GetThumbnail(Model.Photo)}
        </dd>

        <dt>
            Department
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.Name)
        </dd>

        <dt>
            Program
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Program.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OnlineAdmissionSystem/Views/Applications/Edit.cshtml
@*@model OnlineAdmissionSystem.Models.Application*@
@using OnlineAdmissionSystem.Helpers
@model OnlineAdmissionSystem.Models.ApplicationViewModel
@using OnlineAdmissionSystem.Models

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Applications", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Application</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationId)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelePhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Photo" accept="image/x-png,image/gif,image/jpeg" />
                @Html.GetThumbnail(Model.PhotoDB)
            </div>
        </div>

        <!--<div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, "DepartmentId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Department.Name)-->
                @*@Html.DropDownList("DepartmentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })*@
            <!--</div>
        </div>-->

        <div class="form-group">
            @Html.LabelFor(model => model.ProgramId, "ProgramId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProgramId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProgramId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.RegistrationDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (User.IsInRole(RoleName.CanManage))
                {
                    @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                }
                else
                {
                    @Html.DisplayFor(model => model.Status)
                }

                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OnlineAdmissionSystem/Views/Applications/Index.cshtml
@using OnlineAdmissionSystem.Helpers
@*@model IEnumerable<OnlineAdmissionSystem.Models.Application>*@
@using PagedList.Mvc
@model PagedList.IPagedList<OnlineAdmissionSystem.Models.Application>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-md-3">
        @using (Ajax.BeginForm("Index", "Applications", new AjaxOptions()
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "grid"
        }))
        {
            <div class="input-group addon">
                <input class="form-control" placeholder="Any words in Name/Email/Department/Program" name="searchString" type="text" value="@ViewBag.currentFilter" />
                @*<button class="btn btn-default" type="submit">Search</button>*@
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </div>
            </div>
        }
    </div>
</div>

<div id="grid">
    @Html.Partial("_SearchList", Model)
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="/signalr/hubs"></script>
    <script>
        $(document).ready(function () {
            var myHub = $.connection.myHub;
            myHub.client.updateClient = function () {
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: '/Applications',
                    success: function (data) {
                        $('#grid').html(data);
                    }
                });
            };
            $.connection.hub.start().done(function () {
            });
        });
    </script>
}