AjaxSignalR/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AjaxSignalR.Models
{
    public class Student
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

AjaxSignalR/Models/StudentData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AjaxSignalR.Models
{
    public class StudentData
    {
        public static List<Student> GetStudents()
        {
            var students = new List<Student>()
            {
                new Student(){ Id=1, Name = "Ricardo"},
                new Student(){ Id=2, Name = "Antonio"}
            };
            return students;
        }
    }
}

AjaxSignalR/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxSignalR.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AjaxSignalR/Controllers/StudentsController.cs
using AjaxSignalR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AjaxSignalR.Controllers
{
    public class StudentsController : Controller
    {
        // GET: Students
        public ActionResult FromAjax()
        {
            var students = StudentData.GetStudents();
            return PartialView("_StudentList", students);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SendToServer(string message)
        {
            MyHub.UpdateFromServer(message);
            return Content("Request message: " + message);
        }

        public ActionResult SignalRExample()
        {
            return View();
        }
    }
}

AjaxSignalR/Views/Students/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div id="grid">

</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $.ajax({
                cache: false,
                type: "GET",
                url: '/Students/FormAjax',
                success: function (data) {
                    $('#grid').html(data);
                }
            });
        });
    </script>

}

AjaxSignalR/Views/Students/SignalRExample.cshtml
@{
    ViewBag.Title = "SignalRExample";
}

<h2>SignalRExample</h2>

<div class="row">
    <div class="col-md-3">
        @using (Ajax.BeginForm("SendToServer", "Students",
                            new AjaxOptions()
                            {
                                HttpMethod = "GET",
                                InsertionMode = InsertionMode.Replace,
                                UpdateTargetId = "requestMsg"
                            }))
        {
            <div class="input-group addon">
                <input class="form-control" placeholder="send message" name="message" type="text" />
                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
        }
    </div>
</div>

<div id="requestMsg">

</div>

<div id="msg">

</div>
@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.1.2.min.js"></script>
    <script src="/signalr/hubs"></script>
    <script>

        $(document).ready(function () {
            var myHub = $.connection.myHub;
            myHub.client.updateClient = function (message) {
                $('#msg').append("<div>" + message + "</div>")
            };
            $.connection.hub.start().done(function () {
            });
        });
    </script>
}